services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "hyper"
      POSTGRES_PASSWORD: "hyperadmin"
      POSTGRES_DB: "hyperlego"
  server:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://hyper:hyperadmin@db:5432/hyperlego?schema=public"
      PORT: 3000
